package dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Match;

public class MatchRepository extends RepositoryBase<Match> implements IMatchRepository {

	public MatchRepository(Connection connection, IMapResultSetIntoEntity<Match> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}

	@Override
	protected void setInsert(Match entity) throws SQLException {
		insert.setDate(1, (Date) entity.getDate());
		insert.setInt(2, entity.getFirstTeam().getId());
		insert.setInt(3, entity.getSecondTeam().getId());
		insert.setString(4, entity.getResult());
		insert.setInt(5, entity.getBestOf());

	}

	@Override
	protected void setUpdate(Match entity) throws SQLException {
		update.setDate(1, (Date) entity.getDate());
		update.setInt(2, entity.getFirstTeam().getId());
		update.setInt(3, entity.getSecondTeam().getId());
		update.setString(4, entity.getResult());
		update.setInt(5, entity.getBestOf());
	}

	@Override
	protected String tableName() {
		return "match";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE match(" + "id bigint GENERATED BY DEFAULT AS IDENTITY," + "match_date date,"
				+ "firstteam_ID int," + "secondteam_ID int," + "result VARCHAR(20)," + "bestof int,"
				+ "FOREIGN KEY (firstteam_ID) REFERENCES team(id)," 
				+ "FOREIGN KEY (secondteam_ID) REFERENCES team(id)"  + ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO match(match_date,firstteam_ID,secondteam_ID,result,bestof) VALUES(?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE match set match_date=?,firstteam_ID=?,secondteam_ID=?,result=?,bestof=? WHERE id=?";
	}



}
