package dao;

import java.sql.Connection;
import java.sql.SQLException;
import dao.mappers.TeamMemberMapper;
import domain.model.TeamMember;

public class TeamMemberRepository extends RepositoryBase<TeamMember> {


	public TeamMemberRepository(Connection connection, TeamMemberMapper mapper, IRepository<TeamMember> teamMemberRepo) {
		super(connection, mapper);
		mapper.setTeamMemberRepo(teamMemberRepo);
	}

	@Override
	protected void setInsert(TeamMember entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setString(3, entity.getNick());
		insert.setInt(4, entity.getTeamID());
		insert.setInt(5, entity.getAge());
		insert.setString(6, entity.getCountry());
		insert.setString(7, entity.getFavouriteChampion());
		insert.executeUpdate();
		
	}

	@Override
	protected void setUpdate(TeamMember entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setString(3, entity.getNick());
		update.setInt(4, entity.getTeamID());
		update.setInt(5, entity.getAge());
		update.setString(6, entity.getCountry());
		update.setString(7, entity.getFavouriteChampion());
		update.setInt(8, entity.getId());
		update.executeUpdate();		
	}

	@Override
	protected String tableName() {
		// TODO Auto-generated method stub
		return "team_member";
	}

	@Override
	protected String createTableSql() {
		// TODO Auto-generated method stub
		return "CREATE TABLE team_member(" + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name varchar(50)," + "surname varchar(50)," + "nick varchar(50)," + "Team_Id int," 
				+ "age int,"
				+ "country varchar(30),"
				+ "favourite_champion varchar(30),"+ ")";
	}

	@Override
	protected String insertSql() {
		// TODO Auto-generated method stub
		return "INSERT INTO team_member(name, surname, nick, team_id, age, country, favourite_champion) VALUES(?,?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		// TODO Auto-generated method stub
		return "UPDATE team_member SET name=?,surname=?,nick=?,team_id=?,age=?,country=?,favourite_champion=? WHERE id=?";
	}

}
